apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3-replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: mendhak/http-https-echo
        ports:
        - containerPort: 8080
