apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2-replicas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: mendhak/http-https-echo
        ports:
        - containerPort: 80